import React from 'react';
import { Link } from 'react-router-dom';
import { useAppStore } from '../store/appStore';
import { HourlyPlanTable } from '../components/plan/HourlyPlanTable';
import { KPICards } from '../components/plan/KPICards';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Zap } from 'lucide-react';

export default function EnergyPlanPage() {
  const lastResult = useAppStore((state) => state.lastResult);

  if (!lastResult) {
    return (
      <div className="flex flex-col items-center justify-center h-[70vh] animate-in fade-in">
        <div className="bg-bg-panel p-8 rounded-2xl shadow-sm border border-border text-center max-w-md">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-primary-light mb-4">
            <Zap className="h-6 w-6 text-green-600" />
          </div>
          <h3 className="text-lg font-semibold text-text-base mb-2">No Active Plan</h3>
          <p className="text-text-muted mb-6">
            You haven't run an optimization yet. Please go to the Optimize Energy page to generate a plan.
          </p>
          <Link to="/optimize">
            <Button>Go to Optimize Energy</Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div>
        <h2 className="text-2xl font-bold text-text-base tracking-tight">24-Hour Energy Plan</h2>
        <p className="text-text-muted mt-1">Detailed hourly schedule generated by the MILP solver.</p>
      </div>

      <KPICards data={lastResult} />

      <Card>
        <CardHeader>
          <CardTitle>Plan Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-text-base">{lastResult.plan_summary}</p>
        </CardContent>
      </Card>

      <div className="mt-8">
        <h3 className="text-lg font-semibold text-text-base mb-4">Hourly Schedule</h3>
        <HourlyPlanTable plan={lastResult.hourly_plan} />
      </div>
    </div>
  );
}
